services:
  app:
    build: .
    environment:
      - "spring.datasource.username=postgres"
      - "spring.datasource.password=postgres"
      - "spring.datasource.url=jdbc:postgresql://db:5432/example_db"
      - "app.jwt.secret=z1OtmHiiIFG3Wiz7V3IXUHpm2Txgqaf7nISCBlK3CjAwMeYpIfXFxBd4NaQ57m8V"
    ports:
      - "8080:8080"
    profiles:
      - service

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: {}