services:
  app:
    image: 185.159.128.138:5000/swarn-k8s-example-microservice:latest
    environment:
      - "spring.datasource.username=postgres"
      - "spring.datasource.password=postgres"
      - "spring.datasource.url=jdbc:postgresql://db:5432/example_db"
      - "app.jwt.secret=z1OtmHiiIFG3Wiz7V3IXUHpm2Txgqaf7nISCBlK3CjAwMeYpIfXFxBd4NaQ57m8V"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          cpus: '0.8'
          memory: 512M
    networks:
      - public

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 10s
        condition: on-failure
    networks:
      - public

networks:
  public:
    driver: overlay

volumes:
  pg-data: {}