services:
  app:
    build: Dockerfile
    environment:
      - "spring.datasource.username=postgres"
      - "spring.datasource.password=postgres"
      - "spring.datasource.url=jdbc:postgresql://db:5432/example_db"
      - "app.jwt.secret=z1OtmHiiIFG3Wiz7V3IXUHpm2Txgqaf7nISCBlK3CjAwMeYpIfXFxBd4NaQ57m8V"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  pg-data: {}