services:
  app:
    image: vpolkhovsky/swarm-k8s-example-microservice:latest
    environment:
      - "spring.datasource.url=jdbc:postgresql://db:5432/example_db"
      - "app.jwt.secret=z1OtmHiiIFG3Wiz7V3IXUHpm2Txgqaf7nISCBlK3CjAwMeYpIfXFxBd4NaQ57m8V"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          cpus: '0.8'
          memory: 512M
    secrets:
      - source: db_username
        target: spring.datasource.username
      - source: db_password
        target: spring.datasource.password
    networks:
      - public

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: example_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 10s
        condition: on-failure
    secrets:
      - source: db_username
        target: db_username
      - source: db_password
        target: db_password
    networks:
      - public

networks:
  public:
    driver: overlay

volumes:
  pg-data: {}

secrets:
  db_username:
    external: true
  db_password:
    external: true