random-source:
  random-int: ${random.int(1000,9999)}

spring:
  application:
    name: swarm-k8s-microservice-${random-source.random-int}
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/example_db
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    import: "optional:configtree:/run/secrets/"

logging:
  include-application-name: false

app:
  name: ${spring.application.name}
  jwt:
    secret: ${JWT_SECRET:N99Kfn29kk1K5zslu16SsqxTg27mIyK4Nsm8AqQdUJ0jsuN67qM7iyfWfKYCOcHQ}