apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: db
      labels:
        app: postgres
    spec:
      nodeSelector:
        worker: main
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: example_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: app-secrets-dev
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: app-secrets-dev
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "user" ]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "user" ]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc