apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-dev
data:
  spring.datasource.url: jdbc:postgresql://postgres-service-advanced:5432/example_db
  app.jwt.secret: z1OtmHiiIFG3Wiz7V3IXUHpm2Txgqaf7nISCBlK3CjAwMeYpIfXFxBd4NaQ57m8V
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-dev
type: kubernetes.io/basic-auth
stringData:
  username: secret_username
  password: secret_password